#!/bin/bash

set -e

# install fonts
mkdir -p ~/.fonts/
mkdir -p fonts/
cp $1/*.zip fonts
cd fonts
unzip Cairo.zip && rm -rf Cairo.zip && rm -rf *.txt
unzip Rosario.zip && rm -rf Rosario.zip && rm -rf *.txt
unzip Fira_Mono.zip && rm -rf Fira_Mono.zip && rm -rf *.txt
mv *.ttf ~/.fonts/
cd .. && rm -rf fonts
fc-cache -f -v | echo Continuing...
fc-list | grep Cairo
fc-list | grep Rosario
fc-list | grep "Fira Mono"