#!/bin/bash

set -e

# install fonts
mkdir -p ~/.fonts/
mkdir -p fonts/
cd fonts
wget -O Cairo.zip https://fonts.google.com/download?family=Cairo
unzip Cairo.zip && rm -rf Cairo.zip && rm -rf *.txt
wget -O Rosario.zip https://fonts.google.com/download?family=Rosario
unzip Rosario.zip && rm -rf Rosario.zip && rm -rf *.txt
wget -O JetBrainsMono.zip https://fonts.google.com/download?family=JetBrains+Mono
unzip JetBrainsMono.zip && rm -rf JetBrainsMono.zip && rm -rf *.txt
mv *.ttf ~/.fonts/
cd .. && rm -rf fonts
fc-cache -f -v
fc-list | grep Cairo
fc-list | grep Rosario
fc-list | grep JetBrainsMono
